name: Test
version: '${project.version}'
main: pixelizedgaming.test.Test
api-version: 1.20
authors: [ pixelizedgaming ]
commands:
  gaming:
    usage: /gaming <duration>
    description: hahaa
  balls:
    usage: /balls
    description: baslls

